# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-04 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rootadmin',
            name='role',
        ),
    ]
