# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-05 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_remove_rootadmin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootadmin',
            name='role',
            field=models.CharField(default='RootAdmin', max_length=20),
        ),
    ]
